name: Hello World Workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  Workflow_dispatch:
jobs:
  Hello:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v2
