name: new issue workflow
on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: "Create Comment"
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}! Thanks for opening this issue.
            I will be working on this issue and will update you once I am done.
            Meanwhile, you can check out my other projects at
          reactions: '+1,confused,eyes,heart,hooray,laugh,rocket'
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: gh api -X POST repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments -f body="Hello @${{ github.event.issue.user.login }}! Thanks for opening this issue. I will be working on this issue and will update you once I am done. Meanwhile, you can check out my other projects at" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}